-- create the schema
CREATE SCHEMA waze;

-- create the lambda role
-- NOTE: don't change the placeholder text before provisioning the environment, as we replace it during initial install
CREATE ROLE LAMBDA_ROLE_NAME_PLACEHOLDER LOGIN PASSWORD 'LAMBDA_ROLE_PASSWORD_PLACEHOLDER';

-- setup permissions for the lambda role
GRANT ALL ON SCHEMA waze TO LAMBDA_ROLE_NAME_PLACEHOLDER;
ALTER DEFAULT PRIVILEGES IN SCHEMA waze GRANT ALL ON TABLES TO LAMBDA_ROLE_NAME_PLACEHOLDER;
ALTER DEFAULT PRIVILEGES IN SCHEMA waze GRANT SELECT, USAGE ON SEQUENCES TO LAMBDA_ROLE_NAME_PLACEHOLDER;
ALTER DEFAULT PRIVILEGES IN SCHEMA waze	GRANT EXECUTE ON FUNCTIONS TO LAMBDA_ROLE_NAME_PLACEHOLDER;
ALTER DEFAULT PRIVILEGES IN SCHEMA waze	GRANT USAGE ON TYPES TO LAMBDA_ROLE_NAME_PLACEHOLDER;


-- Create read-only role
-- NOTE: don't change the placeholder text before provisioning the environment, as we replace it during initial install
CREATE ROLE READONLY_ROLE_NAME_PLACEHOLDER LOGIN PASSWORD 'READONLY_ROLE_PASSWORD_PLACEHOLDER';

GRANT USAGE ON SCHEMA waze TO READONLY_ROLE_NAME_PLACEHOLDER;
ALTER DEFAULT PRIVILEGES IN SCHEMA waze GRANT SELECT ON SEQUENCES TO READONLY_ROLE_NAME_PLACEHOLDER;
ALTER DEFAULT PRIVILEGES IN SCHEMA waze GRANT SELECT ON TABLES TO READONLY_ROLE_NAME_PLACEHOLDER;
